repos:
    - repo: local
      hooks:
          - id: npm-test
            name: Run npm test
            entry: bash -c 'cd server && npm run test:nocov'
            language: system
            files: ".*"
